name: Check Existing Branch

on:
  push:
    branches:
      - '*'

jobs:
  check-first-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check if first push
        id: check-push
        run: |
          if [ ! -f first_push_done.txt ]; then
            touch first_push_done.txt
            echo "これはこのブランチへの最初のプッシュです"
          else
            echo "このブランチは以前にプッシュされています。"
          fi
        
      - name: Use the result in later steps
        run: echo "${{ steps.check-push.outputs.stdout }}"
