name: Create Issue for New Branch

on:
  create:
    branches:
      - "*"

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Create Issue
        id: create-issue
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        with:
          title: ${{ github.ref_name }}
          body: |
            ${{ github.ref_name }}
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
